
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Antreas Antoniou  ## put your name
title: 'PhD Student in Data Science doing research in Machine Learning'  ## your title
location: Edinburgh, UK


## Social Profiles
#facebook: http://www.facebook.com  ## your facebook account url
twitter: https://twitter.com/_AntreasAntonio  ## your twitter account url
linkedin: https://www.linkedin.com/in/antreas-antoniou-0692579a/  ## your linkedin account url
github: https://github.com/AntreasAntoniou/
#dribbble: http://www.dribble.com  ## you dribbble account url
#foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
